
server
{
	# Puerto donde escucha el servidor
	listen 4242;

	# Nombre aceptado por el servidor
	server_name localhost;

	# Directorio raíz donde están todos los archivos del sitio
	root ./website;

	# Archivo por defecto cuando se accede a un directorio (ej: /)
	index index.html;

	autoindex off;

	upload_path ./website/uploads/;

	# Tamaño máximo para el cuerpo de una solicitud (ej: subida de archivos)
	client_max_body_size 10M; # Aumentado a 10M para archivos más grandes si hace falta

	allow_methods GET POST;

	#return 301 /nuevo-sitio;

	# Páginas de error personalizadas
	error_page 400 /errors/400.html;
	error_page 403 /errors/403.html;
	error_page 404 /errors/404.html;
	error_page 405 /errors/405.html;
	error_page 413 /errors/413.html;
	error_page 500 /errors/500.html;
	error_page 501 /errors/501.html;
	error_page 505 /errors/505.html;
	error_page 502 503 504 /errors/50x.html;

	####################################################
	# RUTA PRINCIPAL (/)
	# Sirve los archivos estáticos como index.html, about.html, style.css
	####################################################
	location / {
		# Métodos permitidos para archivos estáticos
		allow_methods GET POST DELETE;
		autoindex off;
	}

	####################################################
	# RUTA /uploads -> VER archivos subidos
	# Permite listar y descargar los archivos que ya se han subido.
	####################################################
	location /uploads/ {
		allow_methods GET POST;
		# autoindex on es útil para ver una lista de los archivos subidos
		# si no tienes una página que los liste.
		autoindex on;
	}

	####################################################
	# RUTA /images
	####################################################
	location /images/ {
		allow_methods GET POST;
		autoindex on;
	}


	####################################################
	# RUTA /delete -> BORRAR archivos
	# Esta ruta será manejada por un script CGI.
	# El formulario de borrado en index.html debe apuntar aquí.
	# <form method="POST" action="/cgi-bin/file_delete.py">
	####################################################
	# (No se necesita un bloque 'location' específico si todo va por CGI)
	# La lógica de borrado la gestiona el bloque /cgi-bin/ más abajo.


	####################################################
	# BLOCK DE CGI
	# Aquí está la magia. Cualquier petición que vaya a /cgi-bin/
	# será tratada como un script a ejecutar.
	####################################################
	location /cgi-bin/ {
		# Métodos que tus scripts CGI aceptarán.
		allow_methods GET POST DELETE ;
		cgi_pass .php /usr/bin/php-cgi;
		cgi_pass .py /usr/bin/python3;
	}
}
