


#random comments
#  #random comments # #random comments        						


server   #  #random comments # #random comments        						
{

	# Puerto donde escucha el servidor
	listen 8080;

	# Nombre aceptado por el servidor
	server_name localhost example.com;

	# Directorio raíz donde están todos los archivos del sitio
	root ./website;

	# Archivo por defecto cuando se accede a un directorio (ej: /)
	index index.html;

	# Tamaño máximo para el cuerpo de una solicitud (ej: subida de archivos)
	client_max_body_size 5M; # Aumentado a 10M para archivos más grandes si hace falta

	# Páginas de error personalizadas
	error_page 400 /400.html;
}

server
{
	# Puerto donde escucha el servidor
	listen 8080;

	# Nombre aceptado por el servidor
	server_name localhost example.com;

	# Directorio raíz donde están todos los archivos del sitio
	root ./website;

	# Archivo por defecto cuando se accede a un directorio (ej: /)
	index index.html;

	# Tamaño máximo para el cuerpo de una solicitud (ej: subida de archivos)
	client_max_body_size 5M; # Aumentado a 10M para archivos más grandes si hace falta

	# Páginas de error personalizadas
	error_page 400 /400.html;



