server
{
	# Puerto donde escucha el servidor
	#listen          			8080      ;  #port
	#listen          			localhost      ;   #host
	#listen          			127.0.0.1      ;   #host
	listen          			127.0.0.1:8080      ;  #host+port

	# Nombre aceptado por el servidor
	server_name localhost example.com example44.com           ;

	# Directorio raíz donde están todos los archivos del sitio
	root ./website;

	# Archivo por defecto cuando se accede a un directorio (ej: /)
	index index.html;

	

