server
{

	# Nombre aceptado por el servidor

	# Directorio raíz donde están todos los archivos del sitio
	root ./website;

	# Archivo por defecto cuando se accede a un directorio (ej: /)


	# Tamaño máximo para el cuerpo de una solicitud (ej: subida de archivos)
	 # Aumentado a 10M para archivos más grandes si hace falta

	# Páginas de error personalizadas
	

	return 

}
