server
{
	# Puerto donde escucha el servidor
	#listen          			8080      ;  #port
	#listen          			localhost      ;   #host
	#listen          			127.0.0.1      ;   #host
	listen          			127.0.0.1:8080      

}